name: Print Repository Info

on:
  push:
    branches:
      _´**´

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print repository name and branch
        run: |
         echo "Repository: ${{ github.repository }}"
         echo "Branch: ${{ github.ref_name}}"
   
        
      
