# create a workflow that triggers manually and:
# 1. Print your slogan
# 2. Guess our magic number

name: secret stuff
on: 
  workflow_dispatch:
  
jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vras.SLOGAN }}
    steps:
     - run: echo ${{ vars.SLOGAN }}
     - run: echo $ SLOGAN

 
      
    
  
