# create a workflow that triggers manually and:
# 1. Print your slogan
# 2. Guess our magic number

name: secret stuff
on: 
  workflow_dispatch:
  
jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
    steps:
     - run: echo ${{ vars.SLOGAN }}
     - run: echo $ SLOGAN

# Guess
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MY_MAGIC_NUMBER: ${{ vars.MY_MAGIC_NUMBER }}
    steps:
      - name: Print Magic number
        run: echo ${{ secrets.MY_MAGIC_NUMBER }}
      - name: Print Magic number with e variable
        run: echo $MY_MAGIC_NUMBER

 
      
    
  
